name: mlenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip
  - ipykernel
  - matplotlib==3.10.7
  - numpy==2.3.4
  - pandas==2.3.3
  - seaborn
  - scikit-learn
  - statsmodels
  - imbalanced-learn
  - scipy
  - joblib
  - shap
  - umap